const momentumPass=[
    { "stage": 1, "xp": 0, "reward": "Spark of Discipline 🌱" },
    { "stage": 2, "xp": 50, "reward": "Sunrise Momentum ☀️" },
    { "stage": 3, "xp": 100, "reward": "Wheels in Motion ⚙️" },
    { "stage": 4, "xp": 150, "reward": "Locked-In Focus 🎯" },
    { "stage": 5, "xp": 200, "reward": "Foundation Layered 🧱" },
    { "stage": 6, "xp": 250, "reward": "Crystal Clarity 🔍" },
    { "stage": 7, "xp": 300, "reward": "Power Surge 🔋" },
    { "stage": 8, "xp": 350, "reward": "Flow of Consistency 🔄" },
    { "stage": 9, "xp": 400, "reward": "Mindset Rewired 🧠" },
    { "stage": 10, "xp": 450, "reward": "Eyes on the Prize 🎯" },
    { "stage": 11, "xp": 500, "reward": "Action Over Everything 🛠️" },
    { "stage": 12, "xp": 550, "reward": "Drive Without Distractions 🚘" },
    { "stage": 13, "xp": 600, "reward": "The Hustler’s Pack 💼" },
    { "stage": 14, "xp": 650, "reward": "Ride the Flow 🌊" },
    { "stage": 15, "xp": 700, "reward": "Focus Unleashed 🥇" },
    { "stage": 16, "xp": 750, "reward": "Zen Work Mode 🧘" },
    { "stage": 17, "xp": 800, "reward": "Vision in HD 👁️" },
    { "stage": 18, "xp": 850, "reward": "Crowned Consistency 👑" },
    { "stage": 19, "xp": 900, "reward": "Daily Domination 🔨" },
    { "stage": 20, "xp": 950, "reward": "Fuel from Within 🔥" },
    { "stage": 21, "xp": 1000, "reward": "No Excuse Warrior 🚫" },
    { "stage": 22, "xp": 1050, "reward": "Steel Mindset 🛡️" },
    { "stage": 23, "xp": 1100, "reward": "Master of Self 🧘‍♂️" },
    { "stage": 24, "xp": 1150, "reward": "Finisher's Flame 🏁" },
    { "stage": 25, "xp": 1200, "reward": "Summit Mentality 🧗" },
    { "stage": 26, "xp": 1250, "reward": "Diamond Strength 💎" },
    { "stage": 27, "xp": 1300, "reward": "Alpha Energy 🐺" },
    { "stage": 28, "xp": 1350, "reward": "Legacy in Motion 🏛️" },
    { "stage": 29, "xp": 1400, "reward": "Limitless Drive ♾️" },
    { "stage": 30, "xp": 1450, "reward": "Ascended Form 🔱" }
  ]
  
  