import type { Metadata } from "next"
import "./globals.css"
import NavbarWrapper from "@/AppComponents/NavbarWrapper"
import { Toaster } from "@/components/ui/toaster"
import { SessionProvider } from "next-auth/react"
import { Providers } from "./providers"
import { UserProvider } from "@/contexts/UserDataProviderContext"
import { UserProfileProvider } from "@/contexts/UserProfileProviderContext"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        {/* Wrap the whole layout in the SessionProvider */}
        <Providers>
          <UserProvider>
            <NavbarWrapper />
            <UserProfileProvider>
              {children}
              <Toaster />
            </UserProfileProvider>
          </UserProvider>
        </Providers>
      </body>
    </html>
  )
}
