import type { Metadata } from "next"
import "./globals.css"
import { UserDataProviderContext } from "@/contexts/UserDataProviderContext"
import NavbarWrapper from "@/AppComponents/NavbarWrapper"
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <UserDataProviderContext>
          <NavbarWrapper />
          {children}
          <Toaster />
        </UserDataProviderContext>
      </body>
    </html>
  )
}
