import type { Metadata } from "next"
import "./globals.css"
import { Providers } from "./providers" // Ensure you're not double-wrapping
import { UserProvider } from "@/contexts/UserDataProviderContext"
import { UserProfileProvider } from "@/contexts/UserProfileProviderContext"
import Navbar from "@/features/home/Navbar"
import { Toaster } from "@/components/ui/toaster"
import { ThemeProvider } from "@/AppComponents/ThemeProviders/ThemeProvider"
import { SocketProvider } from "@/contexts/SocketProvider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Figtree:wght@400;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SocketProvider>
            <Providers>
              <UserProvider>
                <Navbar />
                <UserProfileProvider>
                  {children}
                  <Toaster />
                </UserProfileProvider>
              </UserProvider>
            </Providers>
          </SocketProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
